name: Quality Check (Build, Lint, Format, Test, Sonarcloud)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.401'
      - name: Run Build
        run: ./scripts.sh build
      - name: Run Tests
        run: ./scripts.sh test
      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"PAYONE-GmbH_PCP-ServerSDK-DotNet" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build --no-incremental
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
