name: Publish package to NuGet
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.401'
      - name: Run Build
        run: ./scripts.sh build
      # - name: Run Publish
      #   run: ./scripts.sh publish ${{ secrets.NUGET_TOKEN }}
      - name: Zip files
        run: zip -r release.zip lib/PCPServerSDKDotNet/bin/Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
